cluster_config:
  num_workers: 2
  spark_version: 7.3.x-scala2.12
  node_type_id': Standard_DS3_v2
  docker_image:
    url: your-docker-image-url
      basic_auth:
          username: docker-username
          password: docker-password