name: Docker Image Build

on:
  push:
    branches:
      - "test"
  pull_request:
    branches:
      - "test"

jobs:
  files-change-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: files-change-check
        with:
          filters: |
            cluster-image:
              - 'cluster_docker_image/**'
            script-file-codes:
              - 'src/**'
              - 'configs/**'
              - 'requirements.txt'
              - 'Dockerfile'
        env:
          CLUSTER_IMAGE: ${{ steps.files-change-check.outputs.cluster-image }}
          SCRIPT_FILE_CODES: ${{ steps.files-change-check.outputs.script-file-codes }}

  cluster-image:
    needs: [files-change-check]
    if: ${{ needs.files-change-check.outputs.cluster-image == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build cluster Docker image
        run: |
          docker build -t your_username/cluster-image:latest ./cluster_docker_image

  script-file-codes:
    needs: [files-change-check, cluster-image]
    if: ${{ needs.files-change-check.outputs.script-file-codes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build script code Docker image
        run: |
          docker build -t your_username/another-image:latest .
