name: Docker Image Build

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  files-change-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: files-change-check
        with:
          filters: |
            cluster-image:
              - 'cluster_docker_image/**'
            script-file-codes:
              - 'src/**'
              - 'configs/**'
              - 'requirements.txt'
              - 'Dockerfile'
              - 'notebooks/**'
    outputs:
      cluster-image: ${{ steps.files-change-check.outputs.cluster-image }}
      script-file-codes: ${{ steps.files-change-check.outputs.script-file-codes }}

  cluster-image:
    needs: [files-change-check]
    if: ${{ needs.files-change-check.outputs.cluster-image == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build cluster Docker image
        run: |
          docker build -t your_username/cluster-image:latest ./cluster_docker_image

  script-file-codes:
    needs: [files-change-check,cluster-image]
    if: ${{ always() && needs.files-change-check.outputs.script-file-codes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build script code Docker image
        run: |
          docker build -t your_username/another-image:latest .
